package me.itangqi.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.Fuli;

import me.itangqi.greendao.FuliDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fuliDaoConfig;

    private final FuliDao fuliDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fuliDaoConfig = daoConfigMap.get(FuliDao.class).clone();
        fuliDaoConfig.initIdentityScope(type);

        fuliDao = new FuliDao(fuliDaoConfig, this);

        registerDao(Fuli.class, fuliDao);
    }
    
    public void clear() {
        fuliDaoConfig.getIdentityScope().clear();
    }

    public FuliDao getFuliDao() {
        return fuliDao;
    }

}
