package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FULI.
 */
public class Fuli {

    private Long id;
    /** Not-null value. */
    private String who;
    /** Not-null value. */
    private String publishedAt;
    /** Not-null value. */
    private String desc;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String used;
    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private String createdAt;
    /** Not-null value. */
    private String updatedAt;

    public Fuli() {
    }

    public Fuli(Long id) {
        this.id = id;
    }

    public Fuli(Long id, String who, String publishedAt, String desc, String type, String url, String used, String objectId, String createdAt, String updatedAt) {
        this.id = id;
        this.who = who;
        this.publishedAt = publishedAt;
        this.desc = desc;
        this.type = type;
        this.url = url;
        this.used = used;
        this.objectId = objectId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getWho() {
        return who;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWho(String who) {
        this.who = who;
    }

    /** Not-null value. */
    public String getPublishedAt() {
        return publishedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    /** Not-null value. */
    public String getDesc() {
        return desc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getUsed() {
        return used;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsed(String used) {
        this.used = used;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public String getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

}
